### ISSUE TITLE
Does not work with scoped packages

### ISSUE THREAD

**Issue by joebowbeer** [qwertie/testpack#2]
With a scoped package name such as `@foo/bar`, testpack will fail to find the packed file:

`Error: Expected @foo/bar-1.0.0.tgz to exist but it doesn't.`

However, the file created by `npm pack` does exist:

foo-bar-1.0.0.tgz

The problem lies in the pkgName [derivation](https://github.com/qwertie/testpack/blob/master/src/testpack.ts#L359) in runNpmPack:

```
var pkgName = `${pkg['name']}-${pkg['version']}.tgz`
```

**Comment by qwertie** [comment]
Thanks for tracking down the location of the issue. It should be fixed now (v1.1.4).
